### PR TITLE
Project 1: NYT article clone

### PR DESCRIPTION
**Pull request by notlfish**
HTML and CSS for making a static clone of the article on https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0

Objectives for this project:
- Write a professional README file and configure the appropriate linters for the project.
-  Make a webpage (HTML and CSS) that copies the contents of the article referenced above.
- Comply with the project guidelines and send a code review request within the deadline time.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @notlfish and @Luconchi       ! :wave: :wave:

#### You have done well so far, Your project looks really nice and good job using semantic HTML tags. :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.
- - -

### **Recommended**

**General**
- [x] Please add a live link to your readme file.
- [x] Please write a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information. 
- [x] Please add all the necessary linters for this module. You can find them as well as a set of instructions on how to configure it [here](https://github.com/microverseinc/linters-config/tree/master/html-css).

**Section Specific requirements**
- [x] The "Space and Cosmo" nav item on your navbar should be in the same font color and family as the login and subscribe button. Also, remove the blue color inherited from being a link.
- [x] The main image of Alan Guth should be of a smaller size. Kindly alter this.
- [x] Some links on the page still retains the styles that come with being `a` tags. Please fix this.
- [x] Some parts of the main content texts have fonts that are larger than what is on the page. I'll recommend using [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension tool to help with this.
- [x] You are missing certain parts of the page: 
-  The Suggested Letters section,
- The Most Popular section,
- The More in Space and Anatomy,
- The Editor's Picks (at the base of the page just underneath the above mentioned section),
- The footer and, 
- The Copyright section.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by notlfish** [comment]
For this project, I installed the HTML and CSS linter, as per instructions. What other linters should I install?

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @notlfish and @Luconchi       ! :wave: :wave:

#### You have done well implementing most of the previously required changes :clap: However, there are changes required for you to make in order for this project to be approved. **_Note that you have one more review on this project before you reach the review limit, so make all of the required changes before submitting for a review._**
- - -

### **Recommended**

**General**
- [x] Please add all the necessary linter files for this module. You can find them as well as a set of instructions on how to configure it [here](https://github.com/microverseinc/linters-config/tree/master/html-css). It seems you might have installed them locally but you still need to add those files to the root of your project as stated in the setup instructions.

**Section Specific requirements**
- [x] The Editors' Picks sidebar : the images are bleeding into the text, please add some spacing between them. It should be positioned beside the paragraph with a small "thank you" note above it.
**Original**

Screenshot (123).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @notlfish! You have done a great job. The website appears to be remarkable. Nice work implementing the changes requested by the previous TSEs. This PR is now approved. You can go ahead and merge the branch. Congratulation and good luck with your next project.

**Pull request merged**
